author = "CamerMedias"
description = "essentielcameroun.com"
license = "MIT"
name = "L'essentiel du Cameroun"
source_repo = "git@github.com:keichi/vienna.git"
tags = ["presse", "information", "cmeroun"]
